# Подготовка окружения для соревнования

In [84]:
#!pip install ipython-autotime kaggle --quiet
%load_ext autotime

The autotime extension is already loaded. To reload it, use:
  %reload_ext autotime
time: 0 ns (started: 2024-12-13 00:08:47 +03:00)


In [2]:
import torch

torch.cuda.is_available()

False

time: 22.3 s (started: 2024-12-12 23:02:13 +03:00)


In [ ]:
# # Optionally, you can dowload the data right here, if you have Kaggle api token (kaggle.json)

# # Upload your token
# from google.colab import files
# files.upload()

# !mkdir -p ~/.kaggle
# !cp kaggle.json ~/.kaggle/
# !chmod 600 /root/.kaggle/kaggle.json

# ! kaggle competitions download -c are-they-alive
# ! unzip -q /content/are-they-alive.zip

Saving kaggle.json to kaggle.json
 82% 63.0M/77.1M [00:00<00:00, 219MB/s]
100% 77.1M/77.1M [00:00<00:00, 132MB/s]
time: 8.35 s (started: 2024-12-09 18:04:39 +00:00)


# ВАШЕ РЕШЕНИЕ

---

## Загрузка данных

In [85]:
train_dataset_dir = "content/train_dataset"
test_dataset_dir = "content/test_dataset"

time: 0 ns (started: 2024-12-13 00:08:52 +03:00)


In [86]:
import torchvision
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader

# Define transformations
transform = torchvision.transforms.Compose([
    torchvision.transforms.ToTensor(),
])

# Load the train dataset
train_dataset = ImageFolder(root=train_dataset_dir, transform=transform)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

print(f"Loaded train dataset with {len(train_dataset)} samples")
train_dataset[0]

Loaded train dataset with 5000 samples


(tensor([[[0.0000, 0.0000, 0.0000,  ..., 0.5843, 0.4471, 0.3059],
          [0.0000, 0.0000, 0.0000,  ..., 0.6784, 0.5529, 0.4392],
          [0.0000, 0.0000, 0.0000,  ..., 0.6941, 0.5765, 0.4902],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.5843, 0.5098, 0.4118],
          [0.0000, 0.0000, 0.0000,  ..., 0.5922, 0.5373, 0.4706],
          [0.0000, 0.0000, 0.0000,  ..., 0.6000, 0.5647, 0.5255]],
 
         [[0.0000, 0.0000, 0.0000,  ..., 0.5882, 0.4471, 0.3059],
          [0.0000, 0.0000, 0.0000,  ..., 0.6863, 0.5608, 0.4431],
          [0.0000, 0.0000, 0.0000,  ..., 0.7020, 0.5843, 0.4941],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.6000, 0.5216, 0.4235],
          [0.0000, 0.0000, 0.0000,  ..., 0.6078, 0.5529, 0.4824],
          [0.0000, 0.0000, 0.0000,  ..., 0.6157, 0.5804, 0.5373]],
 
         [[0.0000, 0.0000, 0.0000,  ..., 0.5922, 0.4627, 0.3176],
          [0.0000, 0.0000, 0.0000,  ..., 0.6902, 0.5686, 0.4549],
          [0.0000, 0.0000, 0.0000,  ...,

time: 15.9 s (started: 2024-12-13 00:08:54 +03:00)


In [89]:
train_dataset[0]

(tensor([[[0.0000, 0.0000, 0.0000,  ..., 0.5843, 0.4471, 0.3059],
          [0.0000, 0.0000, 0.0000,  ..., 0.6784, 0.5529, 0.4392],
          [0.0000, 0.0000, 0.0000,  ..., 0.6941, 0.5765, 0.4902],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.5843, 0.5098, 0.4118],
          [0.0000, 0.0000, 0.0000,  ..., 0.5922, 0.5373, 0.4706],
          [0.0000, 0.0000, 0.0000,  ..., 0.6000, 0.5647, 0.5255]],
 
         [[0.0000, 0.0000, 0.0000,  ..., 0.5882, 0.4471, 0.3059],
          [0.0000, 0.0000, 0.0000,  ..., 0.6863, 0.5608, 0.4431],
          [0.0000, 0.0000, 0.0000,  ..., 0.7020, 0.5843, 0.4941],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.6000, 0.5216, 0.4235],
          [0.0000, 0.0000, 0.0000,  ..., 0.6078, 0.5529, 0.4824],
          [0.0000, 0.0000, 0.0000,  ..., 0.6157, 0.5804, 0.5373]],
 
         [[0.0000, 0.0000, 0.0000,  ..., 0.5922, 0.4627, 0.3176],
          [0.0000, 0.0000, 0.0000,  ..., 0.6902, 0.5686, 0.4549],
          [0.0000, 0.0000, 0.0000,  ...,

time: 0 ns (started: 2024-12-13 00:09:27 +03:00)


In [ ]:
#train_dataset[0][0]
#b = torch.reshape(train_dataset[0][0], (3,4,32,32))

time: 0 ns (started: 2024-12-11 20:42:38 +03:00)


In [81]:
tens = torch.tensor([
                    [[111,112],
                    [121,122]],
                    [[211,212],
                    [221,222]],
                    [[311,312],
                    [321,322]]
               ])
#t = torch.reshape(t, (3, 4,1))
tens[1]



tensor([[211, 212],
        [221, 222]])

time: 0 ns (started: 2024-12-13 00:07:32 +03:00)


In [141]:
from itertools import permutations
from tqdm import tqdm

def create_images(x):
    x, label = x[0], x[1]
    permuts = list(permutations([0, 1, 2, 3], 4))
    t = x.view((3, 4, 32, 32))
    new_images = []

    for order in tqdm(permuts):

        new_image = []
        for layer in range(3):
            image_layer = t[layer]
            print(image_layer)
            new_image.append(torch.tensor([image_layer[i] for i in order]))
        
        new_image = torch.stack(new_image, dim=0)
        new_image = torch.reshape(new_image, (3,64,64))
        print(new_image)

        new_images.append((new_image, label))

create_images(train_dataset[0])

  0%|          | 0/24 [00:00<?, ?it/s]

tensor([[[0.0000, 0.0000, 0.0000,  ..., 0.2980, 0.1059, 0.0235],
         [0.0000, 0.0000, 0.0000,  ..., 0.5843, 0.4471, 0.3059],
         [0.0000, 0.0000, 0.0000,  ..., 0.3490, 0.2196, 0.0784],
         ...,
         [0.8863, 0.8941, 0.8941,  ..., 0.7216, 0.5059, 0.2980],
         [0.3294, 0.3255, 0.3255,  ..., 0.1059, 0.0941, 0.0863],
         [0.9059, 0.9059, 0.8941,  ..., 0.7451, 0.5451, 0.3451]],

        [[0.3137, 0.3059, 0.3020,  ..., 0.0902, 0.0824, 0.0784],
         [0.9216, 0.9137, 0.8902,  ..., 0.8118, 0.6784, 0.4549],
         [0.2941, 0.2863, 0.2784,  ..., 0.0824, 0.0706, 0.0706],
         ...,
         [0.5412, 0.5569, 0.6784,  ..., 0.0863, 0.0863, 0.0863],
         [0.0000, 0.0157, 0.0392,  ..., 0.0118, 0.0078, 0.0000],
         [0.5961, 0.5569, 0.6000,  ..., 0.0706, 0.0627, 0.0549]],

        [[0.0000, 0.0000, 0.0039,  ..., 0.0627, 0.0000, 0.0000],
         [0.3098, 0.3020, 0.2941,  ..., 0.2275, 0.2157, 0.2353],
         [0.0000, 0.0157, 0.0706,  ..., 0.1804, 0.0471, 0.

ValueError: only one element tensors can be converted to Python scalars

time: 47 ms (started: 2024-12-13 00:31:16 +03:00)


In [122]:
t = train_dataset[0][0]
t[0][1]

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0353,
        0.1412, 0.3137, 0.4510, 0.5020, 0.5020, 0.4941, 0.4863, 0.4745, 0.4706,
        0.4667, 0.4706, 0.4706, 0.4627, 0.4588, 0.4549, 0.4588, 0.4627, 0.4431,
        0.4196, 0.3961, 0.3490, 0.2196, 0.0784, 0.0000, 0.0000, 0.0000, 0.0118,
        0.0353, 0.1176, 0.2863, 0.4706, 0.6392, 0.7765, 0.8588, 0.9059, 0.9255,
        0.9333, 0.9333, 0.9294, 0.9176, 0.8431, 0.7569, 0.6510, 0.5333, 0.4275,
        0.3412, 0.2824, 0.3765, 0.4980, 0.6118, 0.6980, 0.7294, 0.6784, 0.5529,
        0.4392])

time: 0 ns (started: 2024-12-13 00:18:55 +03:00)


In [123]:
t = torch.reshape(t,(3,4,32,32))
t[0][0][2]

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0353,
        0.1412, 0.3137, 0.4510, 0.5020, 0.5020, 0.4941, 0.4863, 0.4745, 0.4706,
        0.4667, 0.4706, 0.4706, 0.4627, 0.4588, 0.4549, 0.4588, 0.4627, 0.4431,
        0.4196, 0.3961, 0.3490, 0.2196, 0.0784])

time: 16 ms (started: 2024-12-13 00:18:56 +03:00)


In [5]:
from pathlib import Path
import torchvision.models as models
from torch.utils.data import Dataset, DataLoader
from PIL import Image

class CustomImageDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.root_dir = Path(root_dir)
        self.transform = transform
        self.images = list(self.root_dir.glob('*'))

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = self.images[idx]
        image = Image.open(img_path)
        if self.transform:
            image = self.transform(image)
        return image, img_path.name

# Define the transformation to be applied to the images
transform = torchvision.transforms.Compose([
    torchvision.transforms.ToTensor(),
])

# Create a custom dataset from the folder containing the images
test_dataset = CustomImageDataset(root_dir=test_dataset_dir, transform=transform)

# Create a dataloader to load the images in batches
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

print(f"Loaded test dataset with {len(test_dataset)} samples")

test_dataset[0]

Loaded test dataset with 5000 samples


(tensor([[[0.8745, 0.8824, 0.8863,  ..., 0.0000, 0.0000, 0.0000],
          [0.6275, 0.6706, 0.7059,  ..., 0.0157, 0.0078, 0.0039],
          [0.5922, 0.5843, 0.5686,  ..., 0.0510, 0.0353, 0.0235],
          ...,
          [0.0000, 0.0000, 0.0039,  ..., 0.0039, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
 
         [[0.6941, 0.7255, 0.7373,  ..., 0.0000, 0.0000, 0.0000],
          [0.5176, 0.6039, 0.6627,  ..., 0.0157, 0.0078, 0.0039],
          [0.6196, 0.6314, 0.6275,  ..., 0.0510, 0.0353, 0.0235],
          ...,
          [0.0000, 0.0000, 0.0039,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
 
         [[0.7255, 0.7569, 0.7569,  ..., 0.0000, 0.0000, 0.0000],
          [0.6000, 0.6745, 0.7176,  ..., 0.0157, 0.0078, 0.0039],
          [0.7216, 0.7255, 0.7176,  ...,

time: 344 ms (started: 2024-12-11 23:36:51 +03:00)


## Инициализация модели

In [140]:
from torch import nn
import torch.nn.functional as F

class MyNet(nn.Module):
    def __init__(self):
      super().__init__()
      self.input_layer = nn.Conv2d(3, 8, kernel_size=3)
      self.hidden1_layer = nn.Linear(8, 72)
      self.hidden2_layer = nn.Linear(72, 64)
      self.hidden3_layer = nn.Linear(64, 56)
      self.hidden4_layer = nn.Linear(56, 32)
      self.hidden5_layer = nn.Linear(32, 16)
      self.output_layer = nn.Linear(16, 2)
      # define your model here

    def forward(self, x):
       #x = x.view(-1, 3*64*64)
       x = nn.ReLu(self.input_layer(x))
       x = torch.sigmoid(self.hidden1_layer(x))
       x = torch.sigmoid(self.hidden2_layer(x))
       x = torch.sigmoid(self.hidden3_layer(x))
       x = torch.sigmoid(self.hidden4_layer(x))
       x = torch.sigmoid(self.hidden5_layer(x))
       x = torch.sigmoid(self.output_layer(x))
       return x
    
net = MyNet()

time: 0 ns (started: 2024-12-12 01:01:57 +03:00)


In [127]:
print(net)


MyNet(
  (input_layer): Conv2d(3, 8, kernel_size=(3, 3), stride=(1, 1))
  (hidden1_layer): Linear(in_features=8, out_features=72, bias=True)
  (hidden2_layer): Linear(in_features=72, out_features=64, bias=True)
  (hidden3_layer): Linear(in_features=64, out_features=56, bias=True)
  (hidden4_layer): Linear(in_features=56, out_features=32, bias=True)
  (hidden5_layer): Linear(in_features=32, out_features=16, bias=True)
  (output_layer): Linear(in_features=16, out_features=2, bias=True)
)
time: 0 ns (started: 2024-12-12 00:59:45 +03:00)


In [128]:
total_params = sum(p.numel() for p in net.parameters())
print(f"Total number of parameters in the network: {total_params}")
print(f"{total_params > 1_000_000}")

Total number of parameters in the network: 11570
False
time: 0 ns (started: 2024-12-12 00:59:48 +03:00)


## Обучение модели и все остальное

In [129]:
import torch.optim as optim

time: 0 ns (started: 2024-12-12 00:59:54 +03:00)


In [130]:
# do everything you need to get the best result here
loss_function = nn.CrossEntropyLoss()
optimizer = optim.Adam(net.parameters(), lr=0.05)

time: 0 ns (started: 2024-12-12 00:59:56 +03:00)


In [131]:
train_X = [image for image, _ in train_dataset]
train_Y = train_dataset.targets

time: 3.91 s (started: 2024-12-12 00:59:58 +03:00)


In [133]:
train_X = torch.stack(train_X)

time: 234 ms (started: 2024-12-12 01:00:14 +03:00)


In [101]:
train_X.shape

torch.Size([5000, 3, 64, 64])

time: 0 ns (started: 2024-12-12 00:37:28 +03:00)


In [141]:
epochs = 25

for epoch in range(epochs):
    image_k = 1
    optimizer.zero_grad()
    output = net(train_X)
    loss = loss_function(torch.log(output), torch.tensor(train_Y))
    loss.backward()
    optimizer.step()
        
    print(f'Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}')

AttributeError: module 'torch.nn' has no attribute 'ReLu'

time: 63 ms (started: 2024-12-12 01:02:08 +03:00)


In [105]:
images, _ = next(iter(test_loader))


time: 469 ms (started: 2024-12-12 00:39:17 +03:00)


In [107]:
image = images[0]
with torch.no_grad():
    log_prob = net(image)

prob = log_prob.tolist()
prob = prob[0]
print(f'{prob[0]:.4f}, {prob[1]:.4f}')

0.5206, 0.4825
time: 0 ns (started: 2024-12-12 00:39:43 +03:00)


In [108]:
correct = 0
total = 0
with torch.no_grad():
    for images, labels in train_loader:
        output = net(images)
        
        _, predicted = torch.max(output, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f'Accuracy: {100 * correct / total} %')

Accuracy: 49.44 %
time: 5.83 s (started: 2024-12-12 00:39:48 +03:00)


In [111]:
train_Y.count(1)

2528

time: 0 ns (started: 2024-12-12 00:40:41 +03:00)
